apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../backend/k8s/overlays/prod
  - ../../../client/k8s/overlays/prod
namespace: appointme-prod
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: appointme-ingress
