apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/fhswf/appointme/backend
    newTag: 1.32.0-rc.4
patches:
  - path: configmap-patch.yaml
