apiVersion: v1
data:
  API_URL: https://appoint.gawron.cloud/api/v1
  CLIENT_URL: https://appoint.gawron.cloud
  MONGO_URI: mongodb://mongo-bookme:27017/bookme
  BASE_PATH: ""
  CONTACT_INFO: |
    [Prof. Dr. Christian Gawron](https://jupiter.fh-swf.de/team/cgawron)  
    [gawron.christian@fh-swf.de](mailto:gawron.christian@fh-swf.de)  
    [+49 2371 566 1565](tel:+4923715661565)  
    [Raum P.103, Frauenstuhlweg 31, 58644 Iserlohn](geo:51.36785,7.68687)
  TZ: Europe/Berlin
kind: ConfigMap
metadata:
  name: bookme
  namespace: bookme
