apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.passHostHeader: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
  name: appointme-ingress
  namespace: appointme
spec:
  rules:
  - host: appoint.gawron.cloud
    http:
      paths:
      - backend:
          service:
            name: client
            port:
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: appointme
            port:
              number: 5000
        path: /api
        pathType: Prefix
