apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress.yaml
  - mongo-appointme-claim0-persistentvolumeclaim.yaml
  - mongo-appointme-deployment.yaml
  - mongo-service.yaml
