apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/cgawron/bin/kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-appointme
  name: mongo-appointme
  namespace: appointme
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-appointme
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /home/cgawron/bin/kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/traefik: "true"
        io.kompose.service: mongo-appointme
    spec:
      containers:
        - image: mongo
          name: mongo-appointme
          resources: {}
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: mongo-appointme-claim0
      restartPolicy: Always
      volumes:
        - name: mongo-appointme-claim0
          persistentVolumeClaim:
            claimName: mongo-appointme-claim0
status: {}
