apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongo-appointme
  name: mongo-appointme
  namespace: appointme
spec:
  ports:
    - name: mongo-appointme
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongo-appointme
