apiVersion: v1
kind: Secret
metadata:
  name: appointme-secret
  labels:
    app: appointme
type: Opaque
stringData:
  # Email Configuration
  EMAIL_FROM: "gawron.christian@fh-swf.de"
  EMAIL_PASSWORD: "Awgdnm2w$"
  
  # Security Secrets
  JWT_SECRET: "v9K2m5P8jL1h4N7bQ3w6E9rT2y5U8iO1p0A4s"
  CSRF_SECRET: "z3X6c9V2b5N8m1K4j7H0g3F6d9S2a5Q8w1E4r"
  
  # Google OAuth2 Credentials
  CLIENT_ID: "692793330469-6iupo55tt0kelejcie26m4njeckbmnv8.apps.googleusercontent.com"
  CLIENT_SECRET: "dDJ1RVOjssFvEkeZAUGfsyXL"
  
  # OIDC Credentials
  OIDC_CLIENT_SECRET: "uOiOZOf1H7E8Jh0WKoQ17Wij5wwNordU"
  
  # 
  ENCRYPTION_KEY: "3bb6fe30d49a2e17b8db6a4ad0f0298e"
