apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookme-ingress
spec:
  rules:
    - host: appoint-staging.gawron.cloud
      http:
        paths:
          - backend:
              service:
                name: client
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: bookme
                port:
                  number: 5000
            path: /api
            pathType: Prefix
