apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../../backend/k8s/overlays/dev
  - ../../../client/k8s/overlays/dev
namespace: bookme-dev
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: bookme-ingress
